# # Explanation about `glyenzy_enzymes.json`
#
# ## Format
#
# - "name": gene symbol of the enzyme
# - "rules": a list of rules, each rule is a dictionary with the following keys:
#     - "acceptor": the motif recognized by the enzyme
#     - "acceptor_alignment": alignment of the acceptor motif
#     - "rejects": a list of motifs to be rejected
#     - "requires": an optional OR-valued list of context motifs, each with
#       "motif" and "alignment"
#     - "product": the product generated by the enzyme,
#       whose relationship to the acceptor depends on the enzyme type
# - "type": "GT" for glycosyltransferase, "GH" for glycoside hydrolase,
#   or "ST" for sulfotransferase
# - "species": species of the enzyme
devtools::load_all()

# Load required packages
library(jsonlite)
library(purrr)

# Read JSON data
json_data <- jsonlite::fromJSON(
  "data-raw/glyenzy_enzymes.json",
  simplifyVector = FALSE
)

# Check if there are duplicate enzyme names
enzyme_names <- purrr::map_chr(json_data, "name")
if (any(duplicated(enzyme_names))) {
  cli::cli_abort(
    "Duplicate enzyme names found: {.val {enzyme_names[duplicated(enzyme_names)]}}"
  )
}

# Helper function to create enzyme rule from JSON data
.make_enzyme_rule_from_json <- function(rule_data) {
  if (rule_data$acceptor == "") {
    acceptor <- glyrepr::glycan_structure()
  } else {
    acceptor <- glyparse::parse_iupac_condensed(rule_data$acceptor)
  }
  acceptor_alignment <- rule_data$acceptor_alignment

  product <- glyparse::parse_iupac_condensed(rule_data$product)

  if (length(rule_data$rejects) == 0L) {
    rejects <- glyparse::parse_iupac_condensed(character(0))
  } else {
    rejects <- glyparse::parse_iupac_condensed(
      unlist(rule_data$rejects, use.names = FALSE)
    )
  }

  requires_data <- rule_data$requires
  if (is.null(requires_data)) {
    requires_data <- list()
  }
  requires <- purrr::map(requires_data, function(requirement) {
    list(
      motif = glyparse::parse_iupac_condensed(requirement$motif),
      alignment = requirement$alignment
    )
  })

  glyenzy:::new_enzyme_rule(
    acceptor,
    product,
    acceptor_alignment,
    rejects,
    requires
  )
}

# Helper function to create enzyme from JSON data
.make_enzyme_from_json <- function(enzyme_data) {
  name <- enzyme_data$name
  type <- enzyme_data$type
  species <- enzyme_data$species
  rules <- purrr::map(enzyme_data$rules, .make_enzyme_rule_from_json)

  # Create and validate enzyme, and enhance it
  tryCatch(
    {
      enzyme <- glyenzy:::new_enzyme(name, rules, type, species)
      glyenzy:::validate_enzyme(enzyme)
      enzyme <- glyenzy:::enhance_enzyme(enzyme)
    },
    error = function(e) {
      cli::cli_abort("Can't create valid enzyme for {.val {name}}", parent = e)
    }
  )

  enzyme
}

# Create list of enzymes
glyenzy_enzymes <- purrr::map(json_data, .make_enzyme_from_json)

# Set names to gene symbols
names(glyenzy_enzymes) <- enzyme_names

# Save the data
usethis::use_data(glyenzy_enzymes, overwrite = TRUE, internal = TRUE)
