# # Explanation about `glyenzy_enzymes.json`
#
# ## Format
#
# - "name": gene symbol of the enzyme
# - "rules": a list of rules, each rule is a dictionary with the following keys:
#     - "acceptor": the motif recognized by the enzyme
#     - "acceptor_alignment": alignment of the acceptor motif
#     - "rejects": a list of motifs to be rejected
#     - "requires": an optional OR-valued list of context motifs, each with
#       "motif" and "alignment"
#     - "product": the product generated by the enzyme,
#       whose relationship to the acceptor depends on the enzyme type
# - "type": "GT" for glycosyltransferase, "GH" for glycoside hydrolase,
#   or "ST" for sulfotransferase
# - "species": species of the enzyme
# - "glycan_type": null for all glycan classes, or a list containing one or
#   more of "N", "O", "lipid", and "free"
devtools::load_all()

# Load required packages
library(jsonlite)
library(purrr)

# Read JSON data
json_data <- jsonlite::fromJSON(
  "data-raw/glyenzy_enzymes.json",
  simplifyVector = FALSE
)

# Check if there are duplicate enzyme names
enzyme_names <- purrr::map_chr(json_data, "name")
if (any(duplicated(enzyme_names))) {
  cli::cli_abort(
    "Duplicate enzyme names found: {.val {enzyme_names[duplicated(enzyme_names)]}}"
  )
}

# Helper function to create enzyme rule from JSON data
.make_enzyme_rule_from_json <- function(rule_data) {
  if (rule_data$acceptor == "") {
    acceptor <- glyrepr::glycan_structure()
  } else {
    acceptor <- glyparse::parse_iupac_condensed(rule_data$acceptor)
  }
  acceptor_alignment <- rule_data$acceptor_alignment

  product <- glyparse::parse_iupac_condensed(rule_data$product)

  if (length(rule_data$rejects) == 0L) {
    rejects <- glyparse::parse_iupac_condensed(character(0))
  } else {
    rejects <- glyparse::parse_iupac_condensed(
      unlist(rule_data$rejects, use.names = FALSE)
    )
  }

  requires_data <- rule_data$requires
  if (is.null(requires_data)) {
    requires_data <- list()
  }
  requires <- purrr::map(requires_data, function(requirement) {
    list(
      motif = glyparse::parse_iupac_condensed(requirement$motif),
      alignment = requirement$alignment
    )
  })

  rule <- glyenzy:::new_enzyme_rule(
    acceptor,
    product,
    acceptor_alignment,
    rejects,
    requires
  )
  if (length(rule_data$site_constraints) > 0L) {
    # Private conditions are indices in the parsed acceptor motif, or exact
    # ancestor residue/linkage pairs. They are not make_enzyme() arguments.
    constraints <- rule_data$site_constraints
    for (condition in constraints$acceptor_out_degree) {
      checkmate::assert_int(
        condition$node,
        lower = 1L,
        upper = igraph::vcount(glyrepr::get_structure_graphs(acceptor))
      )
      checkmate::assert_int(condition$degree, lower = 0L)
    }
    for (condition in constraints$reject_ancestors) {
      checkmate::assert_string(condition$mono)
      checkmate::assert_string(condition$linkage)
    }
    rule$site_constraints <- constraints
  }
  rule
}

# Helper function to create enzyme from JSON data
.make_enzyme_from_json <- function(enzyme_data) {
  name <- enzyme_data$name
  type <- enzyme_data$type
  species <- enzyme_data$species
  glycan_type <- enzyme_data$glycan_type
  if (!is.null(glycan_type)) {
    glycan_type <- unlist(glycan_type, use.names = FALSE)
  }
  rules <- purrr::map(enzyme_data$rules, .make_enzyme_rule_from_json)

  # Create and validate enzyme, and enhance it
  tryCatch(
    {
      enzyme <- glyenzy:::new_enzyme(
        name,
        rules,
        type,
        species,
        glycan_type = glycan_type
      )
      glyenzy:::validate_enzyme(enzyme)
      enzyme <- glyenzy:::enhance_enzyme(enzyme)
    },
    error = function(e) {
      cli::cli_abort("Can't create valid enzyme for {.val {name}}", parent = e)
    }
  )

  enzyme
}

# Create list of enzymes
glyenzy_enzymes <- purrr::map(json_data, .make_enzyme_from_json)

# Set names to gene symbols
names(glyenzy_enzymes) <- enzyme_names

# Build the independent abstract collection; never append it to ordinary data.
abstract_data <- jsonlite::fromJSON(
  "data-raw/glyenzy_abstract_enzymes.json",
  simplifyVector = FALSE
)
abstract_names <- purrr::map_chr(abstract_data, "name")
checkmate::assert_names(abstract_names, type = "unique")
stopifnot(length(intersect(abstract_names, enzyme_names)) == 0L)
glyenzy_abstract_enzymes <- purrr::map(abstract_data, function(enzyme_data) {
  enzyme <- .make_enzyme_from_json(enzyme_data)
  class(enzyme) <- c("glyenzy_abstract_enzyme", class(enzyme))
  checkmate::assert_choice(
    enzyme_data$localization,
    c("ER", "cis", "medial", "trans")
  )
  enzyme$localization <- enzyme_data$localization
  enzyme
})
names(glyenzy_abstract_enzymes) <- abstract_names

# Save both lists together so regeneration cannot discard either collection.
usethis::use_data(
  glyenzy_enzymes,
  glyenzy_abstract_enzymes,
  overwrite = TRUE,
  internal = TRUE
)
