// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_bfs_search
Rcpp::List cpp_bfs_search(Rcpp::List config, Rcpp::List callbacks);
RcppExport SEXP _glyenzy_cpp_bfs_search(SEXP configSEXP, SEXP callbacksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type config(configSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type callbacks(callbacksSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_bfs_search(config, callbacks));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_glyenzy_cpp_bfs_search", (DL_FUNC) &_glyenzy_cpp_bfs_search, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_glyenzy(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
