#' Apply an Enzyme to a Glycan
#'
#' This function simulates the action of an enzyme on a glycan.
#' It returns all possible products generated by the enzyme with the given glycans.
#'
#' @inheritSection have_enzyme Important notes
#'
#' @param glycans A [glyrepr::glycan_structure()], or a character vector of
#'   glycan structure strings supported by [glyparse::auto_parse()].
#' @param enzyme An [enzyme()] or a gene symbol.
#' @param return_list If `NULL` (default),
#'   return a list of [glyrepr::glycan_structure()] when `glycans` has length greater than 1,
#'   and a single [glyrepr::glycan_structure()] when `glycans` has length 1.
#'   Set to `TRUE` to always return a list.
#'   This can be useful when you are working programmatically with unknown input length.
#'   Note that when `return_list = FALSE` and `length(glycans) > 1`,
#'   an error will be thrown.
#' @param structure_level Output structure level.
#'   `"intact"` keeps the current behavior and returns products with exact
#'   linkages. `"topological"` removes linkages from products.
#'   `"basic"` removes linkages and converts products to generic residues.
#'   The requested level cannot be lower-resolution than the input glycans.
#'
#' @return A [glyrepr::glycan_structure()] vector, or a list of such vectors.
#'
#' @examples
#' library(glyrepr)
#' library(glyparse)
#'
#' # Use `glycan_structure()` and `enzyme()`
#' glycan <- auto_parse("GlcNAc(b1-2)Man(a1-3)[Man(a1-6)]Man(b1-4)GlcNAc(b1-4)GlcNAc(b1-")
#' apply_enzyme(glycan, enzyme("MGAT3"))
#'
#' # Or use characters directly
#' apply_enzyme("GlcNAc(b1-2)Man(a1-3)[Man(a1-6)]Man(b1-4)GlcNAc(b1-4)GlcNAc(b1-", "MGAT3")
#'
#' # Vectorized input
#' glycans <- c(
#'   "GlcNAc(b1-2)Man(a1-3)[Man(a1-6)]Man(b1-4)GlcNAc(b1-4)GlcNAc(b1-",
#'   "GlcNAc(b1-2)Man(a1-3)[GlcNAc(b1-2)Man(a1-6)]Man(b1-4)GlcNAc(b1-4)GlcNAc(b1-"
#' )
#' apply_enzyme(glycans, "MGAT3")
#'
#' @export
apply_enzyme <- function(
  glycans,
  enzyme,
  return_list = NULL,
  structure_level = "intact"
) {
  structure_level <- .validate_structure_level(structure_level)
  glycans <- .process_glycans_arg(
    glycans,
    allow_generic = identical(structure_level, "basic")
  )
  .validate_output_structure_level(glycans, structure_level)
  enzyme <- .process_enzyme_arg(enzyme)
  return_list <- .validate_return_list(return_list, length(glycans))

  res <- .apply_enzyme(glycans, enzyme, structure_level = structure_level)
  .format_result(res, return_list)
}

#' Apply an enzyme to a vector of glycan structures
#'
#' @param glycans A `glyrepr_structure` vector.
#' @param enzyme A `glyenzy_enzyme` object.
#' @param structure_level Output structure level.
#'
#' @returns A list of `glyrepr_structure` vectors, with the same length as `glycans`.
#'   Each element in the list corresponds to the products of the enzyme on the
#'   corresponding glycan in `glycans`.
#' @noRd
.apply_enzyme <- function(glycans, enzyme, structure_level = "intact") {
  UseMethod(".apply_enzyme", enzyme)
}

.apply_enzyme.glyenzy_starter_gt_enzyme <- function(
  glycans,
  enzyme,
  structure_level = "intact"
) {
  rep(list(glyrepr::glycan_structure()), length(glycans))
}

.apply_enzyme.glyenzy_npre_gt_enzyme <- function(
  glycans,
  enzyme,
  structure_level = "intact"
) {
  rep(list(glyrepr::glycan_structure()), length(glycans))
}

.apply_enzyme.glyenzy_gt_enzyme <- function(
  glycans,
  enzyme,
  structure_level = "intact"
) {
  .apply_enzyme_rules(glycans, enzyme, structure_level = structure_level)
}

.apply_enzyme.glyenzy_gh_enzyme <- function(
  glycans,
  enzyme,
  structure_level = "intact"
) {
  .apply_enzyme_rules(glycans, enzyme, structure_level = structure_level)
}

#' Apply all enzyme rules to a vector of glycan structures
#'
#' @param glycans A `glyrepr_structure` vector.
#' @param enzyme A `glyenzy_enzyme` object.
#' @param structure_level Output structure level.
#'
#' @returns A list of `glyrepr_structure` vectors.
#' @noRd
.apply_enzyme_rules <- function(glycans, enzyme, structure_level = "intact") {
  rule_res <- purrr::map(
    enzyme$rules,
    ~ .apply_rule(glycans, .x, enzyme, structure_level = structure_level)
  )
  res <- purrr::pmap(rule_res, c)
  purrr::map(res, unique)
}

#' Apply an enzyme rule to a vector of glycan structures
#'
#' @param glycans A `glyrepr_structure` vector.
#' @param rule A `glyenzy_enzyme_rule` object.
#' @param enzyme A `glyenzy_enzyme` object.
#' @param structure_level Output structure level.
#'
#' @returns A list of `glyrepr_structure` vectors, with the same length as `glycans`.
#'   Each element in the list corresponds to the products of the enzyme on the
#'   corresponding glycan in `glycans`.
#' @noRd
.apply_rule <- function(
  glycans,
  rule,
  enzyme,
  structure_level = "intact"
) {
  rule_matches <- .match_rule(glycans, rule)
  glyrepr::smap2(
    glycans,
    rule_matches,
    ~ .apply_rule_single(
      .x,
      .y,
      rule,
      enzyme,
      structure_level = structure_level
    )
  )
}

#' Apply a single rule to a glycan graph
#'
#' @param graph An igraph object representing the glycan structure.
#' @param match_res A list of integer vectors, representing the node mapping from the acceptor to the glycan.
#' @param rule A `glyenzy_enzyme_rule` object.
#' @param enzyme A `glyenzy_enzyme` object.
#' @param structure_level Output structure level.
#'
#' @returns A list of `glyrepr_structure` vectors, with the same length as `match_res`.
#' @noRd
.apply_rule_single <- function(
  graph,
  match_res,
  rule,
  enzyme,
  structure_level = "intact"
) {
  indices_to_act_on <- purrr::map_int(match_res, ~ .x[rule$acceptor_idx])
  graph_list <- .apply_rule_action(
    enzyme,
    graph,
    indices_to_act_on,
    rule,
    structure_level = structure_level
  )
  graph_list <- purrr::compact(graph_list)
  .reduce_structure_level(
    glyrepr::as_glycan_structure(graph_list),
    structure_level
  )
}

#' Apply an enzyme-specific graph action
#'
#' @param enzyme A `glyenzy_enzyme` object.
#' @param graph An igraph object representing the glycan structure.
#' @param indices_to_act_on Integer node indices.
#' @param rule A `glyenzy_enzyme_rule` object.
#' @param structure_level Output structure level.
#'
#' @returns A list of igraph objects.
#' @noRd
.apply_rule_action <- function(
  enzyme,
  graph,
  indices_to_act_on,
  rule,
  structure_level = "intact"
) {
  UseMethod(".apply_rule_action", enzyme)
}

.apply_rule_action.glyenzy_gt_enzyme <- function(
  enzyme,
  graph,
  indices_to_act_on,
  rule,
  structure_level = "intact"
) {
  use_basic_graph_edit <- (identical(structure_level, "basic") &&
    .graph_has_generic_monosaccharides(graph))
  residue <- .new_residue_for_graph_edit(rule$new_residue, use_basic_graph_edit)
  linkage <- .new_linkage_for_graph_edit(rule$new_linkage, use_basic_graph_edit)
  purrr::map(
    indices_to_act_on,
    ~ .add_residue(graph, .x, residue, linkage)
  )
}

.apply_rule_action.glyenzy_gh_enzyme <- function(
  enzyme,
  graph,
  indices_to_act_on,
  rule,
  structure_level = "intact"
) {
  purrr::map(indices_to_act_on, ~ .remove_residue(graph, .x))
}

.apply_rule_action.glyenzy_enzyme <- function(
  enzyme,
  graph,
  indices_to_act_on,
  rule,
  structure_level = "intact"
) {
  switch(
    enzyme$type,
    GT = .apply_rule_action.glyenzy_gt_enzyme(
      enzyme,
      graph,
      indices_to_act_on,
      rule,
      structure_level = structure_level
    ),
    GH = .apply_rule_action.glyenzy_gh_enzyme(
      enzyme,
      graph,
      indices_to_act_on,
      rule,
      structure_level = structure_level
    ),
    cli::cli_abort("Unsupported enzyme type: {enzyme$type}")
  )
}

#' Check whether a graph already uses generic monosaccharides
#'
#' @param graph An igraph object representing a glycan structure.
#' @returns A logical scalar.
#' @noRd
.graph_has_generic_monosaccharides <- function(graph) {
  all(glyrepr::get_mono_type(igraph::V(graph)$mono) == "generic")
}

#' Convert a newly added residue for reduced-level graph editing
#'
#' @param residue Concrete monosaccharide name.
#' @param use_basic_graph_edit Whether the target graph is already basic.
#' @returns A monosaccharide name.
#' @noRd
.new_residue_for_graph_edit <- function(residue, use_basic_graph_edit) {
  if (use_basic_graph_edit) {
    return(glyrepr::convert_to_generic(residue))
  }
  residue
}

#' Convert a newly added linkage for reduced-level graph editing
#'
#' @param linkage Concrete linkage string.
#' @param use_basic_graph_edit Whether the target graph is already basic.
#' @returns A linkage string.
#' @noRd
.new_linkage_for_graph_edit <- function(linkage, use_basic_graph_edit) {
  if (use_basic_graph_edit) {
    return("??-?")
  }
  linkage
}

#' Match a rule's acceptor on a glycan structure
#'
#' @param glycans A `glyrepr_structure` vector
#' @param rule A `glyenzy_enzyme_rule` object.
#'
#' @returns A nested list with two layers: the outer layer corresponds to the
#'   glycans in `glycans`, and the inner layer corresponds to different matches
#'   of the rule on the corresponding glycan.
#' @noRd
.match_rule <- function(glycans, rule) {
  res <- .match_motif(
    glycans,
    rule$acceptor,
    alignment = rule$acceptor_alignment
  )
  if (length(rule$rejects) > 0) {
    rej_match_res <- .match_motifs(
      glycans,
      rule$rejects,
      alignments = rule$acceptor_alignment
    )
    res <- .reject_matches(res, rej_match_res)
  }
  res
}

#' Update the match results of the acceptor to exclude the reject matches
#'
#' @param acc_match_res A nested list with two layers: the outer layer corresponds to the
#'   glycans in `glycans`, and the inner layer corresponds to different matches
#'   of the rule on the corresponding glycan.
#' @param rej_match_res A nested list with three layers: the outermost layer corresponds to the
#'   reject motifs, the middle layer corresponds to the glycans, and the innermost layer corresponds to
#'   different matches of the reject on the corresponding glycan.
#'
#' @returns An updated version of `acc_match_res` to exclude the reject matches.
#' @noRd
.reject_matches <- function(acc_match_res, rej_match_res) {
  updated_res <- vector("list", length(acc_match_res))
  for (i in seq_along(acc_match_res)) {
    # i means the i-th glycan

    # ===== Reject Matching Algorithm Details =====

    # For each glycan, it can have multiple matches of the acceptor.
    # Each match is a integer vector of the node indices in the glycan that are matched.
    # Also, for each glycan, it can have multiple matches of the reject motifs (yes, maybe more than one reject motifs).
    # A match is considered to be "valid" if it is not a subset of any reject match.
    # Note that we don't care which motif the reject match is from,
    # because any reject motif can cause the enzyme to reject the glycan match.

    # ===== End of Reject Matching Algorithm Details =====

    acc_match_i <- acc_match_res[[i]] # unknown length
    rej_match_i <- purrr::map(rej_match_res, purrr::pluck, i) # outer: length(rule$rejects), inner: unknown length
    rej_match_i <- purrr::list_flatten(rej_match_i)
    to_reject_i <- purrr::map_lgl(
      acc_match_i,
      .reject_one_match,
      rej_matches = rej_match_i
    )
    updated_res[[i]] <- acc_match_i[!to_reject_i]
  }
  updated_res
}

#' Whether to reject one glycan match based on the reject matches
#'
#' @param acc_match A integer vector, one match result of the acceptor on a glycan.
#' @param rej_matches All matches of the reject motifs on the same glycan.
#'
#' @returns A logical scalar, TRUE if the match should be rejected, FALSE otherwise.
#' @noRd
.reject_one_match <- function(acc_match, rej_matches) {
  is_subset_of <- function(a, b) all(a %in% b)
  purrr::some(rej_matches, ~ is_subset_of(acc_match, .x))
}

#' Add a residue to a glycan graph
#'
#' @param graph An igraph object representing the glycan structure.
#' @param idx_to_add_on The index of the node to add the new residue on.
#' @param new_residue The new residue "mono" to add.
#' @param new_linkage The "linkage" of the new residue.
#'
#' @returns A new igraph object with the new residue added,
#'   or NULL if the new residue cannot be added.
#' @noRd
.add_residue <- function(graph, idx_to_add_on, new_residue, new_linkage) {
  idx_to_add <- igraph::vcount(graph) + 1
  new_graph <- graph
  new_graph <- igraph::add_vertices(
    new_graph,
    1,
    attr = list(name = idx_to_add, mono = new_residue, sub = "")
  )
  new_graph <- igraph::add_edges(
    new_graph,
    c(idx_to_add_on, idx_to_add),
    attr = list(linkage = new_linkage)
  )
  tryCatch(
    {
      glyrepr:::validate_single_glycan_structure(new_graph)
    },
    error = function(e) return(NULL)
  )
}

#' Remove a residue from a glycan graph
#'
#' Only allow removing a terminal (leaf) residue. If the target residue has
#' children (i.e., out-degree > 0), the removal would split the tree into a
#' forest and violate the out-tree invariant. In such cases, return NULL so the
#' caller can drop this invalid product.
#'
#' @param graph An igraph object representing the glycan structure.
#' @param idx_to_remove The index of the node to remove.
#'
#' @returns A new igraph object with the residue removed, or NULL when the
#'   residue is not terminal.
#' @noRd
.remove_residue <- function(graph, idx_to_remove) {
  # Ensure the residue is terminal; otherwise, removing it breaks the out-tree
  if (igraph::degree(graph, v = idx_to_remove, mode = "out") > 0) {
    return(NULL)
  }
  edges <- igraph::incident(graph, idx_to_remove, mode = "all")
  new_graph <- igraph::delete_edges(graph, edges)
  new_graph <- igraph::delete_vertices(new_graph, idx_to_remove)
  # Reset vertex names to maintain consistency with indices after deletion
  igraph::V(new_graph)$name <- as.character(seq_len(igraph::vcount(new_graph)))
  # Validate; if invalid for any reason, signal caller to drop it
  tryCatch(
    {
      glyrepr:::validate_single_glycan_structure(new_graph)
    },
    error = function(e) return(NULL)
  )
}
