#' Enzymes
#'
#' @description
#' Two types of enzymes are involved in glycosylation: glycosyltransferases (GTs) and glycoside hydrolases (GHs).
#' - GTs catalyze the transfer of a sugar residue from a donor to an acceptor, thus building up glycan structures.
#' - GHs catalyze the removal of a sugar residue from a substrate, thus breaking down glycan structures.
#'
#' One special subtype of GTs are starter GTs (or initiating GTs),
#' which catalyze the addition of the first sugar residue onto a non-glycan substrate, thus initiating glycosylation.
#'
#' Use `enzyme()` with a gene symbol to load a predefined enzyme.
#' For example, use `enzyme("ST3GAL3")` to load the enzyme ST3GAL3.
#'
#' Throughout the package, you can use `enzyme()`s for any `enzyme` argument,
#' or just use the gene symbol directly.
#' For example, `involve("Neu5Ac(a2-3)Gal(b1-3)GalNAc(a1-", "ST3GAL3")` and
#' `involve("Neu5Ac(a2-3)Gal(b1-3)GalNAc(a1-", enzyme("ST3GAL3"))` are equivalent.
#'
#' @details
#'
#' # Explanation about `glyenzy_enzyme`
#'
#' An `enzyme()` is a list with the following elements:
#'
#' 1. `name`: the name of the enzyme, usually the gene symbol.
#' 2. `rules`: a list of `glyenzy_enzyme_rule` objects.
#'    Each rule is a list with the following fields:
#'    - `acceptor`: the motif that the enzyme recognizes
#'    - `acceptor_alignment`: the alignment of the `acceptor`
#'    - `rejects`: the motifs that the enzyme rejects to act on
#'    - `product`: the product generated by the enzyme
#'    - `acceptor_idx`: the node index of the acceptor where the enzyme acts on.
#'      For GTs, this is the node new residue is attached to.
#'      For GHs, this is the node that is removed.
#'      For starter GTs, `acceptor_idx` is 0.
#'    - `product_idx`: the node index of the product residue in the product structure.
#'      For GTs, this is the index of the newly added residue in the product.
#'      For GHs, this is `NULL` (no new residue is added).
#'    - `new_residue`: the new residue added by the enzyme. For GHs, this is `NULL`.
#'    - `new_linkage`: the linkage of the new residue. For GHs, this is `NULL`.
#' 3. `type`: the broad type of the enzyme, "GT" for glycosyltransferase or
#'    "GH" for glycoside hydrolase. Starter GTs are encoded as `type = "GT"`.
#' 4. `species`: the species of the enzyme, e.g. "human" or "mouse".
#'
#' You can see all these information by printing the enzyme object.
#'
#' @param symbol The gene symbol of the enzyme.
#'
#' @return A `glyenzy_enzyme` object.
#'
#' @examples
#' library(glyrepr)
#'
#' enzyme("ST3GAL3")
#'
#' @export
enzyme <- function(symbol) {
  checkmate::assert_string(symbol)
  if (symbol %in% names(glyenzy_enzymes)) {
    glyenzy_enzymes[[symbol]]
  } else {
    cli::cli_abort("Unknown enzyme: {.val {symbol}}.")
  }
}

#' Get all enzymes
#'
#' Return a named list of all built-in enzymes,
#' or a character vector of gene symbols if `return_str` is `TRUE`.
#'
#' @param return_str If `FALSE` (default), returns the enzyme list.
#'   Otherwise returns a character vector of gene symbols.
#' @param include_starter_gt If `TRUE` (default), includes starter GTs in the result.
#'   Starter GTs are enzymes that initiate glycosylation by introducing the first sugar residue onto a non-glycan substrate.
#'   For example, DPAGT1 is the starter GT for N-glycosylation.
#'
#' @returns A list of [enzyme()]s or a character vector.
#' @examples
#' db_enzymes(return_str = TRUE)
#'
#' @export
db_enzymes <- function(return_str = FALSE, include_starter_gt = TRUE) {
  if (include_starter_gt) {
    enzymes <- glyenzy_enzymes
  } else {
    enzymes <- purrr::discard(glyenzy_enzymes, .is_starter_gt)
  }
  if (return_str) {
    return(names(enzymes))
  } else {
    return(enzymes)
  }
}

#' Create a new enzyme object
#'
#' @param name The name of the enzyme.
#' @param rules A list of `glyenzy_enzyme_rule` objects.
#' @param type The type of the enzyme, "GT" for glycosyltransferase or "GH" for glycoside hydrolase.
#' @param species The species of the enzyme, e.g. "human" or "mouse".
#'
#' @return A `glyenzy_enzyme` object.
#' @noRd
new_enzyme <- function(name, rules, type, species) {
  checkmate::assert_string(name)
  checkmate::assert_list(rules, types = "glyenzy_enzyme_rule")
  checkmate::assert_choice(type, c("GT", "GH"))
  checkmate::assert_string(species)

  structure(
    list(name = name, rules = rules, type = type, species = species),
    class = .enzyme_classes(name, type)
  )
}

#' Determine S3 classes for an enzyme
#'
#' Classes:
#' - "glyenzy_enzyme": the base class for all enzymes.
#'   - "glyenzy_gt_enzyme": for glycosyltransferases (GTs).
#'    - "glyenzy_starter_gt_enzyme": for starter GTs.
#'    - "glyenzy_npre_gt_enzyme": for GTs involved in N-glycan precursor synthesis.
#'  - "glyenzy_gh_enzyme": for glycoside hydrolases (GHs).
#'
#' @param name The name of the enzyme.
#' @param type The type of the enzyme, "GT" for glycosyltransferase or "GH" for glycoside hydrolase.
#'
#' @returns A character vector of S3 class names.
#' @noRd
.enzyme_classes <- function(name, type) {
  starter_gts <- c(
    "DPAGT1", "FUT10", "FUT11", "POFUT1", "POFUT2",
    "POGLUT1", "POGLUT2", "POGLUT3", "POMT1", "POMT2",
    "TMTC1", "TMTC2", "TMTC3", "TMTC4",
    paste0("GALNT", 1:19)
  )
  cls <- switch(
    type,
    GT = c("glyenzy_gt_enzyme", "glyenzy_enzyme"),
    GH = c("glyenzy_gh_enzyme", "glyenzy_enzyme")
  )
  if (name %in% starter_gts) {
    cls <- c("glyenzy_starter_gt_enzyme", cls)
  }
  if (stringr::str_starts(name, "ALG")) {
    cls <- c("glyenzy_npre_gt_enzyme", cls)
  }
  cls
}

#' Validate a `glyenzy_enzyme` object
#'
#' @param x A `glyenzy_enzyme` object.
#' @noRd
validate_enzyme <- function(x) {
  checkmate::assert_class(x, "glyenzy_enzyme")
  UseMethod("validate_enzyme", x)
}

#' @export
#' @noRd
validate_enzyme.glyenzy_starter_gt_enzyme <- function(x) {
  purrr::walk(x$rules, validate_enzyme_rule_starter)
  invisible(x)
}

#' @export
#' @noRd
validate_enzyme.glyenzy_gt_enzyme <- function(x) {
  purrr::walk(x$rules, validate_enzyme_rule_gt)
  invisible(x)
}

#' @export
#' @noRd
validate_enzyme.glyenzy_gh_enzyme <- function(x) {
  purrr::walk(x$rules, validate_enzyme_rule_gh)
  invisible(x)
}

#' @export
#' @noRd
validate_enzyme.glyenzy_enzyme <- function(x) {
  switch(
    x$type,
    GT = if (.is_starter_gt(x)) {
      validate_enzyme.glyenzy_starter_gt_enzyme(x)
    } else {
      validate_enzyme.glyenzy_gt_enzyme(x)
    },
    GH = validate_enzyme.glyenzy_gh_enzyme(x),
    cli::cli_abort("Unsupported enzyme type: {x$type}")
  )
  invisible(x)
}

#' Enhance a `glyenzy_enzyme` object
#'
#' This function dispatches on the enzyme class, then enhances all rules with
#' enzyme-type-specific helper functions.
#'
#' @param x A `glyenzy_enzyme` object.
#' @noRd
enhance_enzyme <- function(x) {
  checkmate::assert_class(x, "glyenzy_enzyme")
  UseMethod("enhance_enzyme", x)
}

#' @export
#' @noRd
enhance_enzyme.glyenzy_starter_gt_enzyme <- function(x) {
  x$rules <- purrr::map(x$rules, enhance_enzyme_rule_starter)
  x
}

#' @export
#' @noRd
enhance_enzyme.glyenzy_gt_enzyme <- function(x) {
  x$rules <- purrr::map(x$rules, enhance_enzyme_rule_gt)
  x
}

#' @export
#' @noRd
enhance_enzyme.glyenzy_gh_enzyme <- function(x) {
  x$rules <- purrr::map(x$rules, enhance_enzyme_rule_gh)
  x
}

#' @export
#' @noRd
enhance_enzyme.glyenzy_enzyme <- function(x) {
  switch(
    x$type,
    GT = if (.is_starter_gt(x)) {
      enhance_enzyme.glyenzy_starter_gt_enzyme(x)
    } else {
      enhance_enzyme.glyenzy_gt_enzyme(x)
    },
    GH = enhance_enzyme.glyenzy_gh_enzyme(x),
    cli::cli_abort("Unsupported enzyme type: {x$type}")
  )
}

#' Create a new enzyme rule object
#'
#' An enzyme rule defines one reaction of an enzyme.
#' An enzyme can have multiple rules.
#'
#' @param acceptor A `glyrepr_structure` scalar, representing the motif recognized by the enzyme.
#' @param product A `glyrepr_structure` scalar, representing the product generated by the enzyme.
#' @param acceptor_alignment A character string, representing the alignment of the `acceptor`.
#' @param rejects A `glyrepr_structure` vector, representing the motifs that the enzyme rejects.
#'
#' @noRd
new_enzyme_rule <- function(acceptor, product, acceptor_alignment, rejects) {
  checkmate::assert_class(acceptor, "glyrepr_structure")
  checkmate::assert_class(product, "glyrepr_structure")
  checkmate::assert_choice(
    acceptor_alignment,
    c("substructure", "core", "terminal", "whole")
  )
  checkmate::assert_class(rejects, "glyrepr_structure")

  structure(
    list(
      acceptor = acceptor,
      product = product,
      acceptor_alignment = acceptor_alignment,
      rejects = rejects
    ),
    class = "glyenzy_enzyme_rule"
  )
}

#' Validate fields shared by all enzyme rules
#'
#' @param x A `glyenzy_enzyme_rule` object.
#'
#' @noRd
validate_enzyme_rule_common <- function(x) {
  checkmate::assert_class(x, "glyenzy_enzyme_rule")

  if (length(x$acceptor) > 1) {
    cli::cli_abort("The {.arg acceptor} must be a single structure.")
  }
  if (length(x$product) != 1) {
    cli::cli_abort("The {.arg product} must be a single structure.")
  }

  invisible(x)
}

#' Validate reject rules shared by non-starter enzyme rules
#'
#' @param x A `glyenzy_enzyme_rule` object.
#'
#' @noRd
validate_enzyme_rule_rejects <- function(x) {
  if (length(x$rejects) == 0L) {
    return(invisible(x))
  }

  if (x$acceptor_alignment == "whole") {
    cli::cli_abort(
      "Cannot set {.field rejects} when the acceptor alignment is {.val whole}."
    )
  }
  if (
    !all(glymotif::have_motifs(
      x$rejects,
      x$acceptor,
      alignments = "substructure"
    ))
  ) {
    cli::cli_abort(
      "The {.arg acceptor} must be the substructure of all {.arg rejects}."
    )
  }
  n_mono_acc <- igraph::vcount(glyrepr::get_structure_graphs(
    x$acceptor,
    return_list = FALSE
  ))
  n_mono_rej <- glyrepr::smap_int(x$rejects, ~ igraph::vcount(.x))
  if (any(n_mono_rej == n_mono_acc)) {
    cli::cli_abort(
      "{.field rejects} cannot be the same as {.field acceptor}."
    )
  }

  invisible(x)
}

#' Validate a regular GT enzyme rule
#'
#' @param x A `glyenzy_enzyme_rule` object.
#'
#' @noRd
validate_enzyme_rule_gt <- function(x) {
  validate_enzyme_rule_common(x)
  .check_product_acceptor(x$acceptor, x$product, "acceptor", "product")
  validate_enzyme_rule_rejects(x)
  invisible(x)
}

#' Validate a starter GT enzyme rule
#'
#' @param x A `glyenzy_enzyme_rule` object.
#'
#' @noRd
validate_enzyme_rule_starter <- function(x) {
  validate_enzyme_rule_common(x)
  if (length(x$rejects) > 0) {
    cli::cli_abort("{.field rejects} must be empty for starter GTs.")
  }
  invisible(x)
}

#' Validate a GH enzyme rule
#'
#' @param x A `glyenzy_enzyme_rule` object.
#'
#' @noRd
validate_enzyme_rule_gh <- function(x) {
  validate_enzyme_rule_common(x)
  .check_product_acceptor(x$product, x$acceptor, "product", "acceptor")
  validate_enzyme_rule_rejects(x)
  invisible(x)
}

#' Enhance a starter GT rule
#'
#' @param x A starter `glyenzy_enzyme_rule` object.
#'
#' @returns A starter `glyenzy_enzyme_rule` with derived rule fields.
#' @noRd
enhance_enzyme_rule_starter <- function(x) {
  product_graph <- glyrepr::get_structure_graphs(x$product, return_list = FALSE)

  x$acceptor_idx <- 0L
  x$product_idx <- 1L
  x$new_residue <- igraph::V(product_graph)[[1]]$mono
  x$new_linkage <- NULL
  x
}

#' Enhance a regular GT rule
#'
#' @param x A `glyenzy_enzyme_rule` object.
#'
#' @returns An enhanced `glyenzy_enzyme_rule`.
#' @noRd
enhance_enzyme_rule_gt <- function(x) {
  acceptor_graph <- glyrepr::get_structure_graphs(
    x$acceptor,
    return_list = FALSE
  )
  product_graph <- glyrepr::get_structure_graphs(x$product, return_list = FALSE)
  match_res <- glymotif::match_motif(
    x$product,
    x$acceptor,
    alignment = "core"
  )[[1]][[1]] # only one glycan and one match, so `[[1]][[1]]`

  # The node index of the new residue in the product
  new_residue_idx <- setdiff(1:igraph::vcount(product_graph), match_res)

  # Get the index of its parent node
  parent_idx <- igraph::neighbors(product_graph, new_residue_idx, mode = "in")
  # And map it to the acceptor graph
  acceptor_idx <- match(parent_idx, match_res)

  # Get the new residue and new linkage
  new_residue <- igraph::V(product_graph)[new_residue_idx]$mono
  new_linkage <- igraph::incident(
    product_graph,
    new_residue_idx,
    mode = "in"
  )$linkage

  # Add new fields
  x$acceptor_idx <- acceptor_idx
  x$product_idx <- new_residue_idx # For GT: index of newly added residue in product
  x$new_residue <- new_residue
  x$new_linkage <- new_linkage
  x
}

#' Enhance a GH rule
#'
#' @param x A `glyenzy_enzyme_rule` object.
#'
#' @returns An enhanced `glyenzy_enzyme_rule`.
#' @noRd
enhance_enzyme_rule_gh <- function(x) {
  acceptor_graph <- glyrepr::get_structure_graphs(
    x$acceptor,
    return_list = FALSE
  )
  product_graph <- glyrepr::get_structure_graphs(x$product, return_list = FALSE)
  match_res <- glymotif::match_motif(
    x$acceptor,
    x$product,
    alignment = "core"
  )[[1]][[1]] # only one glycan, so `[[1]]`

  # The node index of the removed residue in the acceptor
  removed_residue_idx <- setdiff(1:igraph::vcount(acceptor_graph), match_res)

  # Add new fields
  x$acceptor_idx <- removed_residue_idx
  x$product_idx <- NULL # For GH: no new residue is added
  x$new_residue <- NULL
  x$new_linkage <- NULL
  x
}

#' Check a product-acceptor pair
#'
#' This function checks if a product-acceptor pair is valid.
#' To be a valid pair, the following conditions must be met:
#' 1. `smaller` is a substructure of `larger`
#' 2. `larger` has exactly one more residue than `smaller`
#'
#' @param smaller A `glyrepr_structure` scalar representing the smaller structure.
#' @param larger A `glyrepr_structure` scalar representing the larger structure.
#' @param smaller_name A character string representing the name of the smaller structure.
#'   Used for error messages.
#' @param larger_name A character string representing the name of the larger structure.
#'   Used for error messages.
#'
#' @noRd
.check_product_acceptor <- function(
  smaller,
  larger,
  smaller_name,
  larger_name
) {
  smaller_graph <- glyrepr::get_structure_graphs(smaller, return_list = FALSE)
  larger_graph <- glyrepr::get_structure_graphs(larger, return_list = FALSE)
  match_res <- glymotif::match_motif(larger, smaller, alignment = "core")[[1]] # only one glycan, so `[[1]]`
  # `smaller` is a substructure of `larger`
  if (length(match_res) != 1) {
    cli::cli_abort(
      "{.arg {smaller_name}} must be a substructure of {.arg {larger_name}}."
    )
  }
  match_res <- match_res[[1]] # only one match, so `[[1]]`
  # `larger` has only one more residue than `smaller`
  if (igraph::vcount(larger_graph) - igraph::vcount(smaller_graph) != 1) {
    cli::cli_abort(
      "{.arg {larger_name}} must have exactly one more residue than {.arg {smaller_name}}."
    )
  }
}

#' Check a product-acceptor pair for starter GTs
#'
#' This function checks if a product-acceptor pair is valid for starter GTs.
#' @param acceptor A `glyrepr_structure` scalar representing the acceptor structure.
#' @param product A `glyrepr_structure` scalar representing the product structure.
#' @noRd
.check_starter_product_acceptor <- function(acceptor, product) {
  if (length(acceptor) != 0) {
    cli::cli_abort("The acceptor must be an empty {.cls glyrepr_structure} vector for starter GTs.")
  }
  n_mono <- glyrepr::count_mono(product)
  if (length(n_mono) != 1L || n_mono != 1L) {
    cli::cli_abort(
      "{.arg product} must be a monosaccharide for a starter GT."
    )
  }
  invisible(NULL)
}

#' Check whether an enzyme is a starter GT
#'
#' @param x A `glyenzy_enzyme` object.
#'
#' @returns `TRUE` if `x` is a GT enzyme with at least one empty acceptor rule.
#' @noRd
.is_starter_gt <- function(x) {
  inherits(x, "glyenzy_starter_gt_enzyme")
}

#' Print method for glyenzy_enzyme objects
#'
#' @param x A `glyenzy_enzyme` object.
#' @param ... Additional arguments passed to print methods.
#' @export
print.glyenzy_enzyme <- function(x, ...) {
  cli::cli_h1("Enzyme: {.field {x$name}}")

  # Basic information
  type_str <- .enzyme_type_label(x)
  cli::cli_alert_info("Type: {.val {x$type}} ({.emph {type_str}})")
  cli::cli_alert_info("Species: {.val {x$species}}")

  # Rules section
  cli::cli_h2("Rules ({.val {length(x$rules)}})")
  if (length(x$rules) > 0) {
    purrr::iwalk(x$rules, function(rule, i) {
      cli::cli_alert(
        "Rule {.val {i}}: {.field {rule$acceptor_alignment}} alignment"
      )
      cli::cli_text("  Acceptor: {.val {as.character(rule$acceptor)}}")
      cli::cli_text("  Product:  {.val {as.character(rule$product)}}")

      # Show rejects for this rule
      if (length(rule$rejects) > 0) {
        cli::cli_text("  Rejects:")
        purrr::iwalk(rule$rejects, function(reject, j) {
          cli::cli_text("    {.val {as.character(reject)}}")
        })
      }
    })
  } else {
    cli::cli_text("  {.emph No rules defined}")
  }

  invisible(x)
}

#' Get a printable enzyme type label
#'
#' @param x A `glyenzy_enzyme` object.
#'
#' @returns A character string.
#' @noRd
.enzyme_type_label <- function(x) {
  UseMethod(".enzyme_type_label", x)
}

.enzyme_type_label.glyenzy_starter_gt_enzyme <- function(x) {
  "Starter glycosyltransferase"
}

.enzyme_type_label.glyenzy_npre_gt_enzyme <- function(x) {
  "Glycosyltransferase for N-glycan precursor synthesis"
}

.enzyme_type_label.glyenzy_gt_enzyme <- function(x) {
  "Glycosyltransferase"
}

.enzyme_type_label.glyenzy_gh_enzyme <- function(x) {
  "Glycoside hydrolase"
}

.enzyme_type_label.glyenzy_enzyme <- function(x) {
  switch(
    x$type,
    GT = if (.is_starter_gt(x)) {
      .enzyme_type_label.glyenzy_starter_gt_enzyme(x)
    } else {
      .enzyme_type_label.glyenzy_gt_enzyme(x)
    },
    GH = .enzyme_type_label.glyenzy_gh_enzyme(x),
    cli::cli_abort("Unsupported enzyme type: {x$type}")
  )
}
